-- Your SQL goes here
CREATE TABLE posts ( 
  id INTEGER NOT NULL PRIMARY KEY,
  title VARCHAR NOT NULL, 
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
)
